alias: GrowCube Weekly Watering Summary
trigger:
  - platform: time
    at: "20:00:00"
condition:
  - condition: template
    value_template: "{{ now().weekday() == 6 }}"
action:
  - variables:
      week_log: "{{ state_attr('sensor.growcube_watering_log', 'week') or {} }}"
      current_week: "{{ now().strftime('%G-W%V') }}"
      entries: "{{ week_log.get(current_week, []) }}"
      message: |
        🌿 **GrowCube Weekly Summary ({{ current_week }})**

        {% if entries | length > 0 %}
        The following watering events occurred this week:
        {{ entries | join('\n') }}
        {% else %}
        No watering events recorded this week.
        {% endif %}
  - service: notify.email_notify
    data:
      title: "🗓️ GrowCube Weekly Summary"
      message: "{{ message }}"
mode: single