alias: GrowCube Daily Watering Summary
trigger:
  - platform: time
    at: "20:00:00"
condition: []
action:
  - variables:
      today: "{{ state_attr('sensor.growcube_watering_log', 'today') or [] }}"
      message: |
        🌱 **GrowCube Daily Summary**

        {% if today | length > 0 %}
        The following waterings occurred today:
        {{ today | join('\n') }}
        {% else %}
        No plants were watered today.
        {% endif %}
  - service: notify.email_notify
    data:
      title: "💧 GrowCube Daily Summary"
      message: "{{ message }}"
mode: single