alias: GrowCube Reset Daily Log
trigger:
  - platform: time
    at: "23:59:00"
condition: []
action:
  - service: pyscript.set_state
    data:
      entity_id: sensor.growcube_watering_log
      today: []
mode: single