name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: YAML, JSON, and Markdown Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Super-Linter
        uses: github/super-linter@v4
        with:
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          FILTER_REGEX_EXCLUDE: ".github/workflows/*"

  hass-check:
    name: Home Assistant Config Check
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Home Assistant
        run: pip install homeassistant==2025.4.0
      - name: Check HA configuration
        run: hass --script check_config --config .
