# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Super-Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >-
            --lint-yaml
            --lint-json
            --lint-markdown
            --exclude=".github/workflows/*"

  format:
    name: Format Python Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Install formatters
        run: |
          pip install black isort flake8

      - name: Run black
        run: black custom_components/

      - name: Run isort
        run: isort custom_components/

      - name: Run flake8
        run: flake8 custom_components/

      - name: Commit and push changes if any
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add custom_components/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "style: auto-format Python files (black/isort/flake8)"
            git push
          fi

  hass-check:
    name: Home Assistant Config Check
    runs-on: ubuntu-latest
    needs: [lint, format]
    strategy:
      matrix:
        python-version: [3.14]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Home Assistant
        run: pip install homeassistant==2025.4.0

      - name: Check HA configuration
        run: hass --script check_config --config .
